name: LaBlood Monitor Test

on:
  workflow_dispatch:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check current time
        run: |
          echo "LaBlood monitor test"
          date -u
          echo "Japan time:"
          TZ=Asia/Tokyo date
